### ISSUE TITLE
Input delay is present if frontend's FPS is lower than server's tickrate

### ISSUE THREAD

**Issue by eastlund** [EagiZ/pmr#1]
The delay keeps increasing throughout time, might be buffered tick-messages from server that is queued or something similar.

**Comment by eastlund** [comment]
Problem still exists after my latest commit 0bee947c7544883d7bc33720b25688bf7340bae7 but there's no longer a delay if frontend has been out of focus for a period of time.

**Comment by aekh** [comment]
This problem seems to be resolved after commit 45fe0d104eddfccf12f6b09e9cad7d58b01da894.
